### PR TITLE
Use custom set php binary in migrations task.

### PR DESCRIPTION
**Pull request by glenncoppens**
solves #25 (not tested)

### CODE REVIEW

**Comment by glenncoppens** [comment]
Could this one also be merged? Apparently it breaks deployments with (my) default php binary which is 5.3.3 :')

**Comment by carakas** [comment]
WoW, you really should update your php version

**Comment by glenncoppens** [comment]
With "(my)" I was referring to the hosting company ;) At least the Plesk php versions are on 5.6 and 7 but not for the CLI. That's what the PR was for :)

**Comment by tijsverkoyen** [comment]
Long over due, sorry. But merged

**Pull request merged**
